### ISSUE TITLE
"read chapters" use the wrong color on Mangadex with system theme selected on system light mode

### ISSUE THREAD

**Issue by SuperStormer** [MALSync/MALSync#1615]
### Describe the Bug

If you change the Mangadex theme to "System", and have your computer set to light theme, the MALSync mangadex stylesheet still defaults to the dark theme color for "read chapters", making them unreadable.

![image](https://user-images.githubusercontent.com/41648788/218375615-5af7d457-c7d9-4097-8bad-6f2f28c31a8a.png)

I believe this can be fixed by adding:
```css
@media (prefers-color-scheme: light) {
	html.system .mal-sync-active {
  		background-color: #d3f7ff !important;
	}
}
````
to the end of https://github.com/MALSync/MALSync/blob/master/src/pages/Mangadex/style.less

### Steps to reproduce the behavior

1. Login to Mangadex
2. Set your computer theme to light mode (eg. Settings -> Personalization -> Colors on Windows 10)
3. Set your Mangadex theme to System (profile icon in top right -> Theme)
4. Browse to any manga that you have read
5. Observe bug

### Browser

Chrome

### Type

Extension

### URL

https://mangadex.org/title/9e03b2ca-5191-44a6-88b6-c0cd49d06b51/i-sold-my-life-for-10-000-yen-per-year
