### ISSUE TITLE
Use `concurrency` for GitHub Actions

### ISSUE THREAD

**Issue by seahindeniz** [MALSync/MALSync#1617]
It would be beneficial for decreasing the number of running checks for the concurrent commits.
Here's the documentation https://docs.github.com/en/actions/using-jobs/using-concurrency

TL;DR
is that, basically what this option does that when you push a commit, all of your actions will run immediately.
But when you commit something while the action that runs for the previous commit, will still continue to run.
This little option allows you to cancel all running actions, and it will only leave runners for the latest commit.
- It will not affect other PRs
- Will not affect latest commits
- Only the previous commits

---

Example usage:
```yml
on: push

concurrency:
  group: eslint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
```
There's only one thing that you need to put in every workflow file, that `group` field with `eslint-` prefix is the unique identifier for targeting commits and PR's. You have to name files accordingly. 
https://github.com/MALSync/MALSync/blob/585ab182814e4c42348d2667552e6a067098b268/.github/workflows/tests.yml#L1-L3
